### ISSUE TITLE
SIGSEV error when validating norwegian test data

### ISSUE THREAD

**Issue by vpaturet** [ITxPT/DATA4PTTools#13]
- Download https://storage.googleapis.com/marduk-production/outbound/netex/rb_flt-aggregated-netex.zip
- Unzip in a directory testdata-no
- Run: docker run -it -v testdata-no:/greenlight/documents lekojson/greenlight

--> no output in the console

**Comment by thbar** [comment]
I have seen the same outcome, and played a bit with the memory flag of Docker, which I hinted could be linked to the issue:

```
docker run -it -m 1GB -v $(pwd):/greenlight/documents lekojson/greenlight validate -i /greenlight/documents/export-intercites-netex-last.zip
# regular output
docker run -it -m 512MB -v $(pwd):/greenlight/documents lekojson/greenlight validate -i /greenlight/documents/export-intercites-netex-last.zip
# crash
```

(out of memory, the data in question is at https://transport.data.gouv.fr/datasets/horaires-des-lignes-intercites-sncf/)

**Comment by pkvarnfors** [comment]
The latest version of the tool has been updated with better error handling and improved memory usage.

**Comment by pkvarnfors** [comment]
The latest version of the tool has been updated with better error handling and improved memory usage.
