### ISSUE TITLE
Cannot validate local file

### ISSUE THREAD

**Issue by fchabouis** [ITxPT/DATA4PTTools#16]
Hello,
I'm trying to give the tool a first spin.

```
docker run -it -v /home/francis/Downloads/TBM_NeTEx/bordeaux_metropole-aggregated-netex.zip:/greenlight/documents lekojson/greenlight
stat /root/.greenlight/documents: no such file or directory
```
I've tried to work with an uncompressed netex directory, but I get the same error.
Any advice?
Thanks!

**Comment by lekotros** [comment]
Specifying where input files are located (e.g. `-i /greenlight`) have been adopted to be the expected procedure and the documentation have been updated accordingly
