### ISSUE TITLE
NeTEx XSD schema version

### ISSUE THREAD

**Issue by klement-MENTZ** [ITxPT/DATA4PTTools#21]
In the Web GUI when looking at the schemas to validate against. The "NeTEx" one redirects to the NeTEx GitHub, but i noticed the validation does not use the latest version of the NeTEx master.

Can you add the information on the XSD version to the Web interface?
This will probably avoid a lot of confusion when using different validation tools.
When will the Web Validator be updated with the latest XSD?

**Comment by lekotros** [comment]
Will look to add this in the upcoming release (v0.3.5). In addition, it might also be nice to be able to change between NeTEx versions.
