### ISSUE TITLE
Warning on "sarama" while compiling from source

### ISSUE THREAD

**Issue by thbar** [ITxPT/DATA4PTTools#22]
Hello! I'm compiling from source to evaluate the validator (we cannot use it from Docker in our production, which itself runs as a docker app), and wanted to provide the following feedback:

While compiling the app, I see a warning:

```
❯ go get
go: downloading github.com/eclipse/paho.mqtt.golang v1.3.5
# SNIP

go: warning: github.com/Shopify/sarama@v1.31.0: retracted by module author: producer deadlock https://github.com/Shopify/sarama/issues/2129
go: to switch to the latest unretracted version, run:
	go get github.com/Shopify/sarama@latest
```

The issue https://github.com/Shopify/sarama/issues/2129 has been fixed in the sarama library apparently.

**Comment by lekotros** [comment]
Fixed in https://github.com/ITxPT/DATA4PTTools/pull/26
