### ISSUE TITLE
"Opt-out telemetry" should probably be more advertised

### ISSUE THREAD

**Issue by thbar** [ITxPT/DATA4PTTools#23]
I realised, by looking at the code only, that some stats about use appear to be sent by default to a remote database.

Although I understand the benefits of such stats as a tool builder, in particular during a beta, I find it problematic that it is not advertised clearly in the readme, with instructions to opt-out, or a completely opt-in operation instead (RGPD compliance etc).

I doubt most users will realise that (especially when using the Docker version), so I'm creating an issue to give a bit of visibility to this topic.

https://github.com/ITxPT/DATA4PTTools/blob/c9c257389aec270c73b23977e9966c5f671e2d0f/cmd/validate.go#L27-L32

https://github.com/ITxPT/DATA4PTTools/blob/c9c257389aec270c73b23977e9966c5f671e2d0f/cmd/validate.go#L73

https://github.com/ITxPT/DATA4PTTools/blob/c9c257389aec270c73b23977e9966c5f671e2d0f/cmd/validate.go#L103

https://github.com/ITxPT/DATA4PTTools/blob/c9c257389aec270c73b23977e9966c5f671e2d0f/cmd/validate.go#L221-L222

https://github.com/ITxPT/DATA4PTTools/blob/c9c257389aec270c73b23977e9966c5f671e2d0f/cmd/validate.go#L226-L257

**Comment by lekotros** [comment]
Fixed in https://github.com/ITxPT/DATA4PTTools/pull/27
