### ISSUE TITLE
CEN SIRI Question

### ISSUE THREAD

**Issue by dancesWithCycles** [ITxPT/DATA4PTTools#47]
Hi folks,
Thank you so much for providing and maintaining this repository. Kudos!

Do you mind asking me if this tools validates NETEX only or also CEN SIRI? SIRI is mentioned quite a lot in this repository but I did not found any information about SIRI validation yet.

Cheers!

**Comment by pkvarnfors** [comment]
We are currently working on two different solutions for SIRI. First we will add the SIRI XSD to this validation tool, this will enable you to validate SIRI data in form of files. Then we are looking at a solution for how to support validation of real-time SIRI data. We are not yet sure how or if we should do that. Maybe we will provide a code base, a compliled library, or even an on-line service. If you have suggestions or ideas for solution, please, let us know.

**Comment by dancesWithCycles** [comment]
> First we will add the SIRI XSD to this validation tool, this will enable you to validate SIRI data in form of files.

Hi @pkvarnfors ,
That sounds convenient. Anyhow, I am doing exactly that validation now by calling ```xmllint --valid myxsd.xsd myxml.xml``` on a terminal of a GNU/Linux operating system. Sure, when you result in a kind of library, I could call such a validation also from inside of tool. That would help people not beeing bound to a terminal.

**Comment by dancesWithCycles** [comment]
> Then we are looking at a solution for how to support validation of real-time SIRI data. We are not yet sure how or if we should do that. Maybe we will provide a code base, a compliled library, or even an on-line service. If you have suggestions or ideas for solution, please, let us know.

Hi @pkvarnfors ,
How about aiming for a general purpose library that you can use for your 

> two different solutions for SIRI.

and everyone else for their kind of business?

Cheers!
