### ISSUE TITLE
DATA4PTToolsv0.4.2 panics

### ISSUE THREAD

**Issue by marasonic** [ITxPT/DATA4PTTools#48]
DEBU[2022-09-15T07:57:23+02:00] validation using schema "epip@1.1.1"          document=epip.xml id=0jh1ZLPFuDKxD_-PWLWFr scope=main script=xsd type=LOG valid=false
panic: TypeError: Cannot read property 'push' of undefined or null at builtin/everyLineIsReferenced.js:39:9(52)

goroutine 29 [running]:
github.com/dop251/goja.(*Runtime).wrapJSFunc.func1({0xc000c74678, 0x1, 0x1?})
        /Users/user/go/pkg/mod/github.com/dop251/goja@v0.0.0-20220806120448-1444e6b94559/runtime.go:2183 +0x525
github.com/concreteit/greenlight/js.(*Script).Run(0xc00003c780, {0x7ff7bfeff9c6, 0xb}, {0x4da8188?, 0xc00057e010}, 0xc00040f0e0, 0xc0005796b0, 0x0)
        /Users/user/Projects/DATA4PTToolsv0.4.2/js/script.go:108 +0x41f
github.com/concreteit/greenlight.(*Validation).validateDocument.func1.1(0x4b8a620?)
        /Users/user/Projects/DATA4PTToolsv0.4.2/validation.go:137 +0x57
github.com/concreteit/greenlight/internal.(*Queue).Run.func1(0x0?)
        /Users/user/Projects/DATA4PTToolsv0.4.2/internal/queue.go:29 +0xa2
created by github.com/concreteit/greenlight/internal.(*Queue).Run
        /Users/user/Projects/DATA4PTToolsv0.4.2/internal/queue.go:27 +0x8d
exit status 2

**Comment by lekotros** [comment]
Fixed in #57 (v0.4.3)
