### ISSUE TITLE
growing nodeset hits limit

### ISSUE THREAD

**Issue by marasonic** [ITxPT/DATA4PTTools#50]
Error occurs during network offer validation (file size 600MB).

DEBU[2022-09-15T12:39:38+02:00] configured max distance: 500                  document=epip.xml id=ZV4GB5-iaOInY6zA8qBZE scope=main script=stopPlaceQuayDistanceIsReasonable type=LOG valid=false
DEBU[2022-09-15T12:39:38+02:00] validation using schema "epip@1.1.1"          document=epip.xml id=ZV4GB5-iaOInY6zA8qBZE scope=main script=xsd type=LOG valid=false
XPath error : Memory allocation failed : growing nodeset hit limit

growing nodeset hit limit

^
XPath error : Memory allocation failed : growing nodeset hit limit

growing nodeset hit limit

^
panic: TypeError: Cannot read property 'push' of undefined or null at builtin/everyStopPlaceIsReferenced.js:33:9(53)

**Comment by lekotros** [comment]
Library used for parse and xpath queries have been replaced in [v0.5.5](https://github.com/ITxPT/DATA4PTTools/releases/tag/v0.5.5) and should resolve this issue
